config/routes.rb
Textacademy::Application.routes.draw do

  root :to => 'home#index'

  resources :contributors, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  get "sign_out" => "sessions#destroy", :as => "sign_out"
  resources :exercises, only: [:new, :create]
  resources :lessons, only: [:index, :show]

  match 'my_exercises' => "contributors#exercises", as: :my_exercises

  match 'twilio/sms' => 'twilio#process_sms'
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
	before_filter :signed_in

	def new
		@exercise = Exercise.new(contributor_id: current_contributor.id, lesson_id: params[:lesson_id])
		@question = Question.new(exercise_id: @exercise.id)
		@answer = Answer.new(exercise_id: @exercise.id)
	end

	def create
		@exercise = Exercise.new(params[:exercise])
		if @exercise.save
			redirect_to @exercise.lesson
		else
			flash[:error] = "Invalid fields"
			render "new"
		end
	end


end

app/views/exercises/new.haml
%header
  %h1
    %a#home{:href => "#{root_path}"}
      %span.white> TEXT
      %span.green> ACADEMY

  %p.right.white
    - if @current_contributor.present?
      %a.nav-link{:href => "#{lessons_path}"}
        LESSONS
      |
      %a.nav-link{:href => "#{sign_out_path}"}
        SIGN OUT
    - else
      %a.sign-up-link.nav-link{:href => "#"}
        SIGN UP
      |
      %a.sign-in-link.nav-link{:href => "#"}
        SIGN IN

.wrapper
	.container.lessons
		.content
			-if flash[:error]
				=flash[:error]

			=form_for @exercise do |f|
				=f.fields_for :question, @question do |question|
					=question.text_area :text, placeholder: "Write your exercise question here.", class: "question-input"

				=f.fields_for :answer, @answer do |answer|
					=answer.text_area :text, placeholder: "Write the answer to your exercise question here.", class: "answer-input"

				=f.hidden_field :contributor_id
				=f.hidden_field :lesson_id

				=f.submit